"""What the calculations objectively show, and the structured exceptions the AI layer works from.

The distinction this module exists to hold is the sharpest one in the specification:

    WRONG    The taxpayer understated sales because invoices were omitted.
    CORRECT  14 e-invoices totalling SAR 420,000 could not be matched to the sales register.

The first is a conclusion about a person. The second is a count and a sum. Everything here is
the second kind, and `status.assert_neutral` runs over every sentence before it leaves — the
same guard the comparison explanations pass, for the same reason.

Two products come out of this file:

**Observations** — sentences an auditor reads. Generated from the comparison results, never
written by hand and never generated by a model.

**Exceptions** — the same facts as structured objects with stable ids, carrying the affected
records and their source files. These are what the AI investigation layer receives. It is
deliberately not handed every row of every spreadsheet: the deterministic layer identifies and
structures what is worth investigating, and the model reasons about *that* plus the evidence
behind it.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from . import pairwise as P
from . import status as S


def _sar(v: float) -> str:
    return f"SAR {abs(v):,.2f}"


@dataclass
class Observation:
    """One thing the calculations show. Descriptive; carries no explanation."""

    id: str
    workstream: str
    pairing: str
    text: str
    amount: float | None = None
    count: int | None = None
    records: list[str] = field(default_factory=list)
    source_files: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {"id": self.id, "workstream": self.workstream, "pairing": self.pairing,
                "text": self.text, "amount": self.amount, "count": self.count,
                "records": self.records[:200], "source_files": self.source_files}


@dataclass
class Exception_:
    """A material observation, structured for the investigation layer to work from."""

    id: str
    workstream: str
    pairing: str
    reconciliation: str
    category: str                     # the VAT treatment, or the match status
    kind: str                         # what shape of exception this is
    a_label: str
    b_label: str
    a_value: float | None
    b_value: float | None
    variance: float | None
    variance_pct: float | None
    affected_count: int
    records: list[str]
    source_files: list[str]
    observation: str
    metric: str
    #: What this exception rests on: one comparison, one shape of disagreement, one set of
    #: records — independent of which metric it happens to be measured in. Two exceptions
    #: sharing a basis are one matter and must never be added together.
    basis: str = ""
    #: The same matter measured in another metric. A VAT difference and the taxable-amount
    #: difference underneath it are one exception read two ways, not two exceptions.
    also_measured: list[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "id": self.id, "workstream": self.workstream, "pairing": self.pairing,
            "reconciliation": self.reconciliation, "category": self.category,
            "kind": self.kind, "metric": self.metric, "basis": self.basis,
            "a_label": self.a_label, "b_label": self.b_label,
            "a_value": self.a_value, "b_value": self.b_value,
            "variance": self.variance, "variance_pct": self.variance_pct,
            "affected_count": self.affected_count,
            "records": self.records[:200], "source_files": self.source_files,
            "observation": self.observation, "also_measured": self.also_measured,
        }


# ---------------------------------------------------------------- exception kinds
OVERALL = "overall-variance"
TREATMENT = "treatment-variance"
UNMATCHED = "unmatched-records"
VALUE = "value-difference"
TIMING = "period-difference"
IDENTIFIER = "missing-identifier"
NOT_RUN = "comparison-not-possible"

KIND_LABEL: dict[str, str] = {
    OVERALL: "Overall variance",
    TREATMENT: "VAT-treatment variance",
    UNMATCHED: "Records on one side only",
    VALUE: "Value difference on matched records",
    TIMING: "Records in different tax periods",
    IDENTIFIER: "Records with no identifier",
    NOT_RUN: "Comparison could not be run",
}

#: Match statuses that become their own exception, and the kind each one is.
_MATCH_KIND: dict[str, str] = {
    P.A_ONLY: UNMATCHED, P.B_ONLY: UNMATCHED,
    P.VALUE_MISMATCH: VALUE, P.VAT_MISMATCH: VALUE,
    P.TREATMENT_MISMATCH: TREATMENT,
    P.PERIOD_MISMATCH: TIMING, P.DATE_MISMATCH: TIMING,
    P.NO_IDENTIFIER: IDENTIFIER,
}


def _files(c: P.Comparison) -> list[str]:
    return [s.origin for s in (c.a, c.b) if s.origin]


def _basis(code: str, kind: str, category: str) -> str:
    """One comparison, one shape of disagreement, one category — whatever it is measured in."""
    return f"{code}|{kind}|{category}"


#: Which metric states a matter when it was measured in more than one. VAT is the money, and
#: the taxable amount underneath it is the same records read a second way.
_METRIC_RANK = {"vat": 0, "taxable": 1, "gross": 2}


def _fold(exceptions: list[Exception_]) -> list[Exception_]:
    """One exception per basis, with the other measurements named on it.

    A difference of SAR 119,000 of VAT and the SAR 793,333 of taxable amount beneath it are the
    same records disagreeing once. Kept as two rows they would be investigated twice, reported
    twice, and — the defect that matters — added together into a figure corresponding to nothing.
    """
    by_basis: dict[str, list[Exception_]] = {}
    for e in exceptions:
        by_basis.setdefault(e.basis, []).append(e)

    out: list[Exception_] = []
    for group in by_basis.values():
        group.sort(key=lambda e: _METRIC_RANK.get(e.metric, 9))
        head, rest = group[0], group[1:]
        head.also_measured = [
            {"metric": e.metric, "metric_label": P.METRIC_LABEL[e.metric],
             "a_value": e.a_value, "b_value": e.b_value, "variance": e.variance,
             "variance_pct": e.variance_pct, "observation": e.observation}
            for e in rest]
        out.append(head)
    return out


def derive(comparisons: list[P.Comparison]) -> tuple[list[Observation], list[Exception_]]:
    """Everything the comparisons show, as sentences and as structured exceptions."""
    observations: list[Observation] = []
    exceptions: list[Exception_] = []
    seq = 0

    def next_id(workstream: str, kind: str) -> str:
        nonlocal seq
        seq += 1
        return f"{workstream[:3].upper()}-{kind.split('-')[0].upper()}-{seq:03d}"

    for c in comparisons:
        code = c.pairing.code
        ws = c.pairing.workstream

        # --- the comparison could not be run at all
        if not c.runnable:
            text = (f"{c.pairing.title} could not be compared: "
                    + "; ".join(c.blocked_by) + ".")
            S.assert_neutral(text, where=code)
            oid = next_id(ws, NOT_RUN)
            observations.append(Observation(id=oid, workstream=ws, pairing=code, text=text,
                                            source_files=_files(c)))
            exceptions.append(Exception_(
                id=oid, workstream=ws, pairing=code, reconciliation=c.pairing.title,
                category="—", kind=NOT_RUN, metric=c.metric,
                a_label=c.a.label, b_label=c.b.label, a_value=None, b_value=None,
                variance=None, variance_pct=None, affected_count=0, records=[],
                source_files=_files(c), observation=text,
                basis=_basis(code, NOT_RUN, "—")))
            continue

        # --- level 1
        # "VAT" is an initialism; lowercasing it reads as a typo in every sentence below.
        metric = P.METRIC_LABEL[c.metric]
        metric = metric if metric == "VAT" else metric.lower()
        # Totals that agree while the records inside them do not is a real and common result —
        # an omission on one side offset by an overstatement on the other. Saying only "the two
        # agree" beside a comparison the engine has marked as a variance would have the sentence
        # contradict the badge above it.
        if c.variance:
            tail = (f", a difference of {_sar(c.variance)}"
                    f"{f' ({abs(c.variance_pct):.1%})' if c.variance_pct else ''}.")
        elif c.status == S.VARIANCE:
            tail = (" — the totals agree, though records within them do not, so the agreement "
                    "is the net of differences in both directions.")
        else:
            tail = " — the two agree."
        text = (f"{c.a.label} shows {_sar(c.a.total or 0)} of {metric} against "
                f"{_sar(c.b.total or 0)} in {c.b.label.lower()}" + tail)
        S.assert_neutral(text, where=code)
        observations.append(Observation(id=next_id(ws, OVERALL), workstream=ws, pairing=code,
                                        text=text, amount=c.variance,
                                        source_files=_files(c)))
        if c.status == S.VARIANCE and c.variance:
            oid = observations[-1].id
            exceptions.append(Exception_(
                id=oid, workstream=ws, pairing=code, reconciliation=c.pairing.title,
                category="Overall", kind=OVERALL, metric=c.metric,
                a_label=c.a.label, b_label=c.b.label,
                a_value=c.a.total, b_value=c.b.total,
                variance=c.variance, variance_pct=c.variance_pct,
                affected_count=(c.a.count or 0) + (c.b.count or 0), records=[],
                source_files=_files(c), observation=text,
                basis=_basis(code, OVERALL, "Overall")))

        # --- level 2. The category that earns this level: totals that broadly agree while a
        #     single VAT treatment inside them does not.
        for t in c.treatments:
            if t.status != S.VARIANCE or not t.variance:
                continue
            text = (f"{t.label} {metric}: {_sar(t.a_total or 0)} in {c.a.label.lower()} against "
                    f"{_sar(t.b_total or 0)} in {c.b.label.lower()}, a difference of "
                    f"{_sar(t.variance)}"
                    + (f" ({abs(t.variance_pct):.1%})" if t.variance_pct else "") + ".")
            S.assert_neutral(text, where=code)
            oid = next_id(ws, TREATMENT)
            observations.append(Observation(id=oid, workstream=ws, pairing=code, text=text,
                                            amount=t.variance,
                                            count=max(t.a_count, t.b_count),
                                            source_files=_files(c)))
            exceptions.append(Exception_(
                id=oid, workstream=ws, pairing=code, reconciliation=c.pairing.title,
                category=t.label, kind=TREATMENT, metric=c.metric,
                a_label=c.a.label, b_label=c.b.label,
                a_value=t.a_total, b_value=t.b_total,
                variance=t.variance, variance_pct=t.variance_pct,
                affected_count=max(t.a_count, t.b_count), records=[],
                source_files=_files(c), observation=text,
                basis=_basis(code, TREATMENT, t.label)))

        # --- level 3, grouped by what kind of disagreement it is
        grouped: dict[str, list[P.MatchRow]] = {}
        for m in c.matches:
            if m.status in P.AGREEING:
                continue
            grouped.setdefault(m.status, []).append(m)

        for match_status, rows in sorted(grouped.items()):
            kind = _MATCH_KIND.get(match_status, UNMATCHED)
            amount = round(sum(abs(r.delta if r.delta is not None
                                   else (r.a_amount or r.b_amount or 0.0)) for r in rows), 2)
            records = [rid for r in rows for rid in (r.a_records + r.b_records)]
            where = (c.a.origin if match_status == P.A_ONLY else
                     c.b.origin if match_status == P.B_ONLY else
                     " and ".join(_files(c)))

            if match_status in (P.A_ONLY, P.B_ONLY):
                other = c.b.label.lower() if match_status == P.A_ONLY else c.a.label.lower()
                text = (f"{len(rows)} record(s) in {where} totalling {_sar(amount)} of {metric} "
                        f"could not be matched to {other}.")
            elif match_status in (P.VALUE_MISMATCH, P.VAT_MISMATCH):
                text = (f"{len(rows)} record(s) present in both sources carry a different "
                        f"{metric}, differing by {_sar(amount)} in total.")
            elif match_status == P.PERIOD_MISMATCH:
                text = (f"{len(rows)} record(s) appear in different tax periods between the two "
                        f"sources. Recorded as a timing difference; whether it is a defect is "
                        f"not settled by these figures.")
            elif match_status == P.DATE_MISMATCH:
                text = f"{len(rows)} record(s) are dated differently by the two sources."
            elif match_status == P.TREATMENT_MISMATCH:
                text = (f"{len(rows)} record(s) are given a different VAT treatment by each "
                        f"source.")
            else:
                text = (f"{len(rows)} record(s) carry no invoice identifier, so they cannot be "
                        f"matched to the other source.")

            S.assert_neutral(text, where=code)
            oid = next_id(ws, kind)
            observations.append(Observation(id=oid, workstream=ws, pairing=code, text=text,
                                            amount=amount, count=len(rows), records=records,
                                            source_files=_files(c)))
            exceptions.append(Exception_(
                id=oid, workstream=ws, pairing=code, reconciliation=c.pairing.title,
                category=P.MATCH_LABEL[match_status], kind=kind, metric=c.metric,
                a_label=c.a.label, b_label=c.b.label, a_value=None, b_value=None,
                variance=amount, variance_pct=None, affected_count=len(rows),
                records=records, source_files=_files(c), observation=text,
                basis=_basis(code, kind, P.MATCH_LABEL[match_status])))

    # Two observations that read identically say nothing twice; the ones that differ by metric
    # each carry their metric in the sentence and are kept.
    seen: set[tuple[str, str]] = set()
    observations = [o for o in observations
                    if (o.pairing, o.text) not in seen
                    and not seen.add((o.pairing, o.text))]

    return observations, _fold(exceptions)
